### ISSUE TITLE
Schema methods support?

### ISSUE THREAD

**Issue by Elyx0** [BetterCallSky/ts-mongoose#13]
When declaring
```javascript
itemSchema.methods.customFunction = function (): number[]{
 return [0,0];
};
```
then using on the 
```javascript
    ...({} as {
        customFunction: () => number;
    }),
``` 
in the `createSchema({`
on my `item` schema I get
```
Type assertion on object literals is forbidden, use a type annotation instead.eslint(@typescript-eslint/no-object-literal-type-assertion)
```

So when I use
```javascript
import Item,{itemDoc} from './item'
function updateItem(item:itemDoc):void {
 // ...
 item.customFunction()
}
``` 
I get a TS error:
```
Property 'customFunction' does not exist on type '{ itemID ... etc'
```

Is there a trick I'm missing?
<img width="576" alt="Screen Shot 2019-06-08 at 4 28 40 AM" src="https://user-images.githubusercontent.com/706218/59144562-cb9b3100-89a7-11e9-9015-28a2030f3429.png">

**Comment by Nayir** [comment]
@Elyx0 , I have the same issue with ItemSchema.virtual.
I guess it don't support it...

**Comment by Elyx0** [comment]
Yeah I guess 319 weekly download and used by 12 repos isn't enough of an incentive for @BetterCallSky to fix yet :/ 
The problem is the first cast with `{} as` seems like a fast trick instead of a stable patch so we're screwed a bit for now.

**Comment by BetterCallSky** [comment]
Sorry for the late response.

Can you provide a full example?

Below code doesn't show any errors.
```ts
const UserSchema = createSchema({
  title: Type.string(),
  author: Type.string(),
  ...({} as {
    generatedField: string;
    customFunction: () => number;
  }),
});

UserSchema.methods.customFunction = () => 123;

const User = typedModel('User', UserSchema);

User.findById('1').then(user => {
  if (user) {
    user.generatedField = '13';
    user.customFunction()
  }
}
```


Also, one of your errors is an error from tslint, not typescript. Unfortunately, this eslint rule must be disabled.

**Comment by shilangyu** [comment]
This is a `eslint` error not `ts-mongoose`'s
