### ISSUE TITLE
Question: required/optional refactor

### ISSUE THREAD

**Issue by lchimaru** [BetterCallSky/ts-mongoose#15]
@BetterCallSky what do you think about small code refactor to mark properties as required/optional to be based on provided options? I mean approach would be the same as it's done in mongoose. So following code:
```ts
{
  email: Type.string()
  username: Type.optionalString(});
}
```
would be converted into:
```ts
{
  email: Type.string({ required: true })
  username: Type.string()
}
```

We would get rid of optionalType, so required option flag would take care of field being required/optional.

I can do that, but I want to be sure you're ok with that.

**Comment by michaelbats** [comment]
What if yo need to have a property optional as typescript interface and required as part of mongoose schema? such as the _id;

Example: have a 'site' object that you send from the frontend and on the backend you generate the random ID and write it to the database. 

Your frontend won't like sending the site object without an _id property to the backend and you'll either have to create a separate interface or send some random string +  account for that specific string on the backend when validating.

I think declaring it like this: `Type.optionalString({required: true})`; comes in handy!

**Comment by lchimaru** [comment]
I think the idea for ts-mongoose library is to create exactly the same type as it is in mongo collection. So the idea of `Type.optionalString({required: true})` has no use case in my opinion.

For your need you might use `Omit<YourDocumentType, '_id'>` helper to get rid of `_id` property from your type.

**Comment by BetterCallSky** [comment]
For me it's ok, if you can do it :wink:
`Type.string({required: true})` will require some work with conditional types in Typescript

**Comment by michaelbats** [comment]
@lchimaru  but I do need the _id in there when I'm reading a document/updating/deleting a document, it's just when I'm creating one that it's not needed. I can't be the only one who's had this problem though?

**Comment by michaelbats** [comment]
I also though one of the points of ts-mongoose is to define everything in one place and be able to use the interface, docs and schemas everywhere, and in most cases you have some keys that you want as optional on the frontend but required on the backend :-?

**Comment by lchimaru** [comment]
Done in `0.0.20`.
