### ISSUE TITLE
Default value null for string -- but not optional!

### ISSUE THREAD

**Issue by michaelbats** [BetterCallSky/ts-mongoose#17]
This is a thing that I might be using wrong myself, but I have had a few use cases when  I wanted to have a 'null' default values for strings that are otherwise 'required' -- I basically needed the field to be there. 

This works ok in practice with mongoose and it does add the key with the value 'null' which is helpful to account for vs an empty string.

Do you think this is something that should be added to reflect the actual mongoose functionality? or is it intentionally not possible to define null as a default value?

**Comment by lchimaru** [comment]
mongoose won't let you create Schema with such property:
```ts
{
  myString: { type: String, required: true, default: null }
}
```
you can skip required flag, but then you will create optional field (in your case it will be always filled). 
For such edge case as yours you might use Type Assertion:
```ts
{
  myString: Type.mixed({ default: null }) as string,
}
```

**Comment by michaelbats** [comment]
@lchimaru  hmmm, for some odd reason using mongoose that way hasn't thrown out any errors in my case, but typescript is indeed now screaming at me trying to do that, I will stop using null's as a default.

Your example with `Type.optionalMixed` makes me think there's a solution to another use-case I was about weirded about. I am using GeoJSON with mapbox and the coordinates property is not an array of numbers but [number. number] an array having exactly 2 items in it that are numbers. Would I do this as:
```
Type.optionalMixed({required: true}) as [number, number];
```

**Comment by lchimaru** [comment]
How you declare it in mongoose? Simple by required array? Like that?
```ts
{
  geo: { type: [Number], required: true }
}
```

for this, you can use `as [number, number]` type assertion with `Type.array().of(Type.number())`, as there is no array length restriction in mongoose.

**Comment by michaelbats** [comment]
In mongoose it was just a simple number array without any limits, but for the frontend and the purposes of GeoJSON it must be [number, number] as a typescript interface. 

I tried it using optionalMixed and works well as typescript interface & mapbox seems happy with it.

Anyhow, this whole package is a great timesaver for me, we're iterating fast over various data models as we approach the beta, being able to affect that model in 1 single place and then have it work everywhere as a mongoose schema and typescript interfaces, across multiple SPA's and backend API it's just incredible vs the mess it used to be changing a data model.

Thanks & great work!

**Comment by lchimaru** [comment]
@michaelbats sure, but be aware, that `Type.optionalMixed()` will return no type for mongoose option object, so you will have no type restriction for creating/updating this field in your model.

All thanks to @BetterCallSky, it's he's idea and most of code :)

**Comment by michaelbats** [comment]
Hmm, then can I use: 
```
Type.array().of(Type.number()) as [number, number];
```
I definitely want to enforce a number array on the mongoose side

**Comment by lchimaru** [comment]
Yup, in my opinion it should fit best in your case.
