### ISSUE TITLE
ExtractProps does not work with subdocuments

### ISSUE THREAD

**Issue by michaelbats** [BetterCallSky/ts-mongoose#18]
Example: 

```

const OrderSchema = createSchema({
  _id: Type.string({ required: true }),
  site: Type.schema({ required: true }).of(SiteSchema),
});
export const Order = typedModel('orders', OrderSchema);
export type IOrder = ExtractProps<typeof OrderSchema>;
```

the result interface objet.site will still have all of the subdocument properties, this is specifically what I get: 

```
Type '{ UPRN: string; UPRNLabel: string; postcode: string; addressLine1: string; title: string; _id: string; clientId: string; city: string; county: string; teamsId: string; }' is missing the following properties from type 'Subdocument': ownerDocument, remove, $isDefault, $session, and 28 more.ts(2322)
```

Am I using this wrong?

**Comment by lchimaru** [comment]
You're using it correctly, `ExtractProps` helper had been done before we added Subdocuments functionality. I'll fix that later.

Btw, you don't need `{ required: true }` option in methods like `Type.string()` for now, they will always return required field.

**Comment by michaelbats** [comment]
Thanks, I just tried refactoring into objects instead of subdocuments so that my subcollections have interfaces as follows: 
``` 
files: Type.optionalArray().of(Type.object().of(GoogleFileObject))
____________
export const GoogleFileObject = {
  fileId: Type.string(),
  fileName: Type.string(),
  fileUrl: Type.string(),
  hideFromEngineer: Type.boolean()
};
```
But now this throws a bunch of errors when trying to use as mongoose schema:

```
TypeError: Invalid schema configuration: `undefined` is not a valid type within the array `files`.See http://bit.ly/mongoose-schematypes for a list of valid schema types.
```

So this gets me thinking that the workaround I had for interfaces won't work for schemas.  

Do you think upgrading ExtractProps to work with subcollections would take a lot of work? Might try to do it myself so I can get this working :-?

**Comment by michaelbats** [comment]
ended up using typegoose
