### ISSUE TITLE
Mongoose aggregation idea/separate project

### ISSUE THREAD

**Issue by michaelbats** [BetterCallSky/ts-mongoose#19]
@BetterCallSky  @lchimaru  I see you two being quite active around here and I looked a bit around if anything like it exists and then thought I'd write here about it to get some outside opinions.

How would you feel about the option of adding type support to mongoo aggregation?

You have your schemas/types and based on each possible type, you generate a placeholder value for each key based on type and some logic depending on the type. 

You configure how many documents you want to simulate based on user-inputed configuration.

Then as you type your aggregation, you return either the simulated end result or ideally the state of your date every aggregation step via intellisense. It would be of immense value for everyone considering how powerful the aggregation is but it's also a lot of work with some unknowns. I'd definitely be willing to participate in developing such tool.

**Comment by lchimaru** [comment]
It seems to be good idea, but I think it's too early for now to implement such thing. There are lot of gaps to be filled before we even start to think about it.
