### ISSUE TITLE
populateTs on simple Item

### ISSUE THREAD

**Issue by gkasser** [BetterCallSky/ts-mongoose#2]
Hi @BetterCallSky ,

Thanks for your package. I have a small Issue and I couldn't find it in the documentation so I would like to know if this is an error or if I have misused it.

my code :

`import { createSchema, Type, typedModel } from 'ts-mongoose';`
`import 'ts-mongoose/plugin'`
``
`const PropSchema = createSchema({`
`	myprop: Type.string()`
`})`
``
`const ExtSchema = createSchema({`
`	myotherprop: Type.string()`
`})`
``
`const UserSchema = createSchema({`
`	email: Type.string({unique: true, required: true}),`
`	username: Type.string({unique: true, required: true }),`
`	password: Type.string(),`
`	extern: Type.ref(Type.objectId()).to('Extern', ExtSchema),`
`	comments: Type.array().of(`
`		Type.ref(Type.objectId()).to('Comments', PropSchema)`
`	),`
`	created_at: Date`
`});`
``
`export async function test() {`
`	const User = typedModel('User', UserSchema);`
`	let user = await User.findById('123').populateTs('extern').populateTs('comments')`
`	if (user) {`
`		let ooo = user.comments // { myprop: string;}[]     OK`
`		let eee = user.extern // mongoose.Types.ObjectId | {myotherprop: string;}    NOK`
`	}`
`}`

Cheers

**Comment by BetterCallSky** [comment]
Hi @gkasser 
Thanks for reporting it, it should be fixed in v0.0.11.

**Comment by gkasser** [comment]
Works perfectly,

Thanks a lot !
