### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by alizahid** [BetterCallSky/ts-mongoose#20]
How do I define a static method on my model?

**Comment by lchimaru** [comment]
Can you provide some example of static method usage?

**Comment by alizahid** [comment]
Say I have this model.

```typescript
const post = createSchema({
  body: Type.string(),
  ratings: Type.array().of(rating), // `rating` is another schema

  ...({} as {
    rate: (user: string, direction: number) => RatingDoc
  })
})

post.statics.rate = function(user: string, direction: number) {
  // do something
}
```

Now, when I use my model somewhere, `rate` doesn't show as a static method. But it does show as an instance method.

```typescript
import Post from './post'

Post.rate(...) // does not exist

const post = new Post()

post.rate(...) // exists
```

**Comment by lchimaru** [comment]
There is no `statics` support in our package, but I think it's doable. I will look at this later.

**Comment by lchimaru** [comment]
@alizahid `statics` support added in `0.0.19`. Check it out, and let me know if there's no gaps.

**Comment by alizahid** [comment]
Thank you. I'll check it out!

**Comment by shilangyu** [comment]
I cannot get it to work, not even the example one. Seems like TS is having a hard time figuring out what `this` refers to

**Comment by lchimaru** [comment]
Have you tried using example from [example6](https://github.com/BetterCallSky/ts-mongoose/blob/feat-static-methods/example/example6.ts)? Do you use latest version of `mongoose`? I would appreciate if you attach screenshot with error.

**Comment by shilangyu** [comment]
## Steps to reproduce:
```sh
> mkdir test && cd test
> npm init -y
> npm i ts-mongoose @types/mongoose mongoose typescript 
> tsc --init
```

Populating `index.ts` with [example6](https://github.com/BetterCallSky/ts-mongoose/blob/feat-static-methods/example/example6.ts) with the changed import:

```ts
import { createSchema, ModelInstancesType, ModelInstanceType, Type, typedModel } from 'ts-mongoose'

const UserSchema = createSchema(
	{
		name: Type.string(),
		age: Type.number()
	},
	{
		statics: {
			findByName: function(name: string): ModelInstancesType {
				return this.find({ name: name })
			},
			findOneByName: function(name: string): ModelInstanceType {
				return this.findOne({ name: name })
			},
			countLetters: function(name: string, bonus?: number): number {
				return name.length + (bonus ? bonus : 0)
			}
		}
	}
)

const User = typedModel('User', UserSchema)

async function test() {
	const users = await User.findByName('John')
	users[0].age
	const user = await User.findOneByName('Michael')
	if (user) {
		user.age
	}

	const nameLength = User.countLetters('123', 3)
}
```

## Result:

`tsc` fails to compile (with 154 errors) and `this` error appears:

![image](https://user-images.githubusercontent.com/29288116/60970749-eb18d700-a322-11e9-997c-7002777cee7e.png)

**Comment by shilangyu** [comment]
Is it even doable with the current implementation? It seems to create a circular typings: 
To get the correct typings in the static methods (declared inside of `createSchema()`) you need to have a `typedModel()` which needs a `createSchema()` etc.

**Comment by lchimaru** [comment]
Sorry guys for you keep you waiting so long, newest version has support for statics (which are declared in declaration of model, not schema like before). Let me know if anything is missing.

**Comment by Corky3892** [comment]
You sir, are a king. I was just about to post a workaround by casting `this` as `any`. I dare say this was a timely release for me.

I have implemented the statics method as outlined in the updated docs and its looking good.

**Comment by uhmtoto** [comment]
> ```ts
> ModelInstanceType
> ```

I can't load `ModelInstanceType` from `ts-mongoose`.
How can I?
