### ISSUE TITLE
TypeError: Invalid schema configuration: `True` is not a valid type at path `required`.

### ISSUE THREAD

**Issue by michaelbats** [BetterCallSky/ts-mongoose#21]
So this error is being thrown with this model:

```ts
const ContactSchema = createSchema({
  _id: Type.string(),
  firstname: Type.string(),
  lastname: Type.string(),
  jobRole: Type.optionalString(),
  email: Type.string(),
  telephone: Type.optionalArray().of(
    Type.object().of({
      type: Type.string(),
      number: Type.string()
    })
  ),
  notes: Type.optionalString(),
  clientId: Type.string(),
  ownerId: Type.string(),
  source: Type.string(),
  status: Type.string({ default: 'active' }) as 'active' | 'inactive',
  tags: Type.optionalArray().of(Type.string()),
  createdAt: Type.date({ default: new Date(Date.now()) })
});
```

There is no 'required: true' configured anywhere, double-checked the compiled files yet the error keeps being thrown out, not exactly sure what's going wrong where/why.

**Comment by lchimaru** [comment]
I wasn't able to reproduce it. Is it failing on compiling? You can try removing properties one by one to check which of them are buggy.

**Comment by michaelbats** [comment]
Couldn't figure out which did what, refactored everything with typegoose

**Comment by rjptechsolutions** [comment]
just remove required: true, were data : Buffer or in Multimedia, IMG format it works for me
