### ISSUE TITLE
Derived Array Methods throwing Typescript Compile Errors when _id is specified in options

### ISSUE THREAD

**Issue by marktdodds** [BetterCallSky/ts-mongoose#32]
The following Mongoose model compiles correctly:

```
import { createSchema, Type, typedModel, ExtractDoc, ExtractProps } from 'ts-mongoose';

const schema = createSchema(
  {
    items: Type.array().of(createSchema({
      someItem: Type.string()
    }, {_id: true})),
  }
);

export const TemplateSchema = typedModel('Template', schema);

const c = async () => {
  const doc = await TemplateSchema.findById('5d8b9533ebc8bf1c264b8817');
  if (!doc) return;
  doc.items.splice(0,1);
};
```

However, if you change `_id` in the schema to `false`, you get the following typescript error at `docs.items.splice(0,1)`:

`Cannot invoke an expression whose type lacks a call signature. Type 'Pick<{ someItem: string; } & {} & Subdocument, "toString" | "get" | "set" | "init" | "validate" | "remove" | "update" | "updateOne" | "id" | "toJSON" | "toObject" | "inspect" | "ownerDocument" | ... 21 more ... | "someItem">' has no compatible call signatures.
`

I believe it should compile regardless of if the schema in the array does or does not have an id.

mongoose: v5.7.1
ts-mongoose: v0.0.19

**Comment by lchimaru** [comment]
Fixed in version `0.0.21`
